development:
  secret_key_base: b9df49b9299621b709bb8090e1d6bd4cd224c4674eea76ef2292ff6c2dac4b577e4075c4a6c53e9e16dfed24ff7ccb7a67514fc26052cb145eaa4463fc4e99de
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  associate_tag: <%= ENV["ASSOCIATE_TAG"] %>
  mws_marketplace_id: <%= ENV["MWS_MARKETPLACE_ID"] %>
  mws_merchant_id: <%= ENV["MWS_MERCHANT_ID"] %>

test:
  secret_key_base: 3b51e756954111f033204566d6c3892963d11285fd17ff250a42595fbefa5c5381946390333de487ff38e5e239eeaa29decff94ba348d67a2c48482b6d8b270e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  associate_tag: <%= ENV["ASSOCIATE_TAG"] %>
  mws_marketplace_id: <%= ENV["MWS_MARKETPLACE_ID"] %>
  mws_merchant_id: <%= ENV["MWS_MERCHANT_ID"] %>